name: fitbuddy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  intl: any
  animate_do: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  source_gen: ^2.0.0
  build_runner: ^2.4.15
  analyzer: ^7.4.5
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/gifs/calentamiento/
    - assets/gifs/cadera/
    - assets/gifs/abdomen_cintura/
    - assets/gifs/piernas_gluteos/
    - assets/gifs/pecho/
    - assets/gifs/biceps_antebrazos/
    - assets/gifs/triceps/
    - assets/gifs/espalda_lumbar/
    - assets/gifs/hombros_trapecios/