name: Flutter Validador

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.3

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: |
          flutter analyze > analyze_output.txt
          cat analyze_output.txt
          if grep -q "error •" analyze_output.txt; then
            echo "Se encontraron errores."
            exit 1
          else
            echo "No hay errores. Ignorando advertencias."
          fi

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug
        
